ros_client:
  ip: "192.168.0.21"  # manager PC
  port: 9090
method:
  file_name: "auto_tma.ngb-s-dil"
  param:
    lab: "room_A"
    project: "sample_project"
    measurer: "operator"
    comment: ""
    #sample_id:  # define in experiment
    sample_name: "test_material"
    sample_length: 20
    sample_width: 5
    #sample_thickness:  # define in experiment
    sample_material: "polyethylene"
    result_file_name: "result_file"
